packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild@0.25.11
  - sharp@0.34.5

strictDepBuilds: true

autoInstallPeers: false
strictPeerDependencies: true
peerDependencyRules:
  allowedVersions:
    astro: ^5

overrides:
  read-package-up: 12.0.0
  read-pkg: 10.0.0
  unicorn-magic: 0.4.0
