packages:
  - packages/*

autoInstallPeers: false

disallowWorkspaceCycles: true

onlyBuiltDependencies:
  - esbuild@0.25.11
  - sharp@0.34.5

overrides:
  read-package-up: 12.0.0
  read-pkg: 10.0.0
  unicorn-magic: 0.4.0

patchedDependencies:
  "@typescript-eslint/project-service@8.50.1": patches/@typescript-eslint__project-service@8.50.1.patch

strictDepBuilds: true

strictPeerDependencies: true
