autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild@0.25.11
  - sharp@0.34.5

overrides:
  read-package-up: 12.0.0
  read-pkg: 10.0.0
  unicorn-magic: 0.4.0

packages:
  - packages/*

peerDependencyRules:
  allowedVersions:
    astro: "5"

strictDepBuilds: true
strictPeerDependencies: true
