body:
  - attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: Bug Report Checklist
      options:
        - label: I am using the latest published version of all Flint packages.
          required: true
        - label: I have [searched for related issues](https://github.com/flint-fyi/flint/issues?q=is%3Aissue) and found none that matched my issue.
          required: true
    type: checkboxes
  - attributes:
      description: A minimal code sample which demonstrates the issue
      label: Reproduction
      render: TypeScript
    type: textarea
    validations:
      required: true
  - attributes:
      description: What did you expect to happen?
      label: Expected
    type: textarea
    validations:
      required: true
  - attributes:
      description: What happened instead?
      label: Actual
    type: textarea
    validations:
      required: true
  - attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
    type: textarea

description: Report a bug specific to a lint rule provided by Flint

labels:
  - "type: bug"

name: 🐛 Lint Rule Bug

title: "🐛 Bug: [plugin.ruleName] <short description of the bug>"
